'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _reduxSaga = require('redux-saga');

var saga = _interopRequireWildcard(_reduxSaga);

var _effects = require('redux-saga/effects');

var _effects2 = _interopRequireDefault(_effects);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

// Generated by CoffeeScript 2.0.0-beta2
var createSagaMiddleware, dispatch, sagaDefault, sagaMiddleware, sagasRun;

sagaDefault = saga.default;

createSagaMiddleware = saga.createSagaMiddleware;


sagaMiddleware = createSagaMiddleware();

sagasRun = function sagasRun(sagas) {
  var i, len, sagaOne;
  for (i = 0, len = sagas.length; i < len; i++) {
    sagaOne = sagas[i];
    sagaMiddleware.run(sagaOne);
  }
};

dispatch = function dispatch(action, actionType) {
  return _effects2.default.put(Object.assign({}, action, {
    type: actionType
  }));
};

exports.default = { saga: saga, sagaDefault: sagaDefault, sagaEffects: _effects2.default, dispatch: dispatch, sagaMiddleware: sagaMiddleware, sagasRun: sagasRun };

