'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Generated by CoffeeScript 2.0.0-beta2
var createSagaMiddleware, dispatch, saga, sagaDefault, sagaEffects;

saga = require('redux-saga');

sagaDefault = saga.default;

sagaEffects = require('redux-saga/effects');

createSagaMiddleware = function createSagaMiddleware(sagas) {
  return sagaDefault.apply(this, sagas);
};

dispatch = function dispatch(action, actionType) {
  return sagaEffects.put(Object.assign({}, action, {
    type: actionType
  }));
};

exports.default = { saga: saga, sagaDefault: sagaDefault, sagaEffects: sagaEffects, createSagaMiddleware: createSagaMiddleware, dispatch: dispatch };

